version: '3.8'

services:
  samples:
    container_name: samples_dev
    image: samples:test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: 'vscode'
        INSTALL_ZSH: 'false'
        UPGRADE_PACKAGES: 'true'

    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:temporalite
    depends_on:
      - temporalite

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  temporalite:
    build:
      context: .
      dockerfile: Dockerfile.temporalite
    image: temporalite:test
    container_name: samples_temporalite
    ports:
      - 7233:7233
    environment:
      TEMPORAL_CLI_ADDRESS: localhost:7233

  web:
    image: temporaliotest/ui:latest
    container_name: samples_web
    depends_on:
      - temporalite
    environment:
      TEMPORAL_ADDRESS: 'localhost:7233'

    network_mode: service:temporalite
    restart: unless-stopped
